portal:
  extends:
    file: _common.yml
    service: portal
  links:
  - "mock:api"
  ports:
  - 8090:8090
  - 35729:35729


mock:
  extends:
    file: _common.yml
    service: mock
  links:
  - "mongo:mongo"
  ports:
  - "5000:5000"


mongo:
  extends:
    file: _common.yml
    service: mongo
