angular
  .module('portal', [
    'ngAnimate',
    'ngRoute',
    'templates',
    'restangular',
    'portal.config',
    'portal.services',
    'portal.directives',
    'portal.controllers',
    'portal.logger',
    'portal.coupons',
    'portal.notifications',
    'portal.home',
    'portal.levels',
    'portal.organizations',
    'portal.users',
    'portal.statistics',
    //'portal.shop',
    'portal.news',
    //'portal.chat',
    'portal.crud'
  ]);
